module.exports = function(sequelize, DataTypes) {
  //this will add the video information to the database
  var Video = sequelize.define("Video", {
    //this puts the title into the database
    title: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: { len: [1] },
    },

    //this adds the description provided by the user into the database
    description: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: { len: [3, 140] },
    },

    //this adds the token generated by ziggeo to the database
    token: {
      type: DataTypes.STRING,
      allowNull: false,
    },

    // thumbnail: {
    //   type: DataTypes.STRING,
    //   allowNull: false,
    // },

    //this adds the category selected
    category: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: { len: [1] },
    },

    //this adds the keyword selected. this is necessary
    keywordOne: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: { len: [1] },
    },

    //this adds a second keyword if provided
    keywordTwo: {
      type: DataTypes.STRING,
      allowNull: true,
    },

    //this adds a third keyword if provided
    keywordThree: {
      type: DataTypes.STRING,
      allowNull: true,
    },
  });

  //this makes sure it is associated with the correct contributor
  Video.associate = function(models) {
    Video.belongsTo(models.Contributor, {
      foreignKey: {
        allowNull: false,
      },
    });
  };

  return Video;
};
